import { openSans } from '@styles/font';
import type { Metadata } from 'next';
import '@styles/globals.css';
import type { ReactNode } from 'react';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Next Template',
  description: 'Generated by create next app',
  robots: 'index, follow',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(openSans.className, openSans.variable)}>{children}</body>
    </html>
  );
}
