name: CI

on:
  push:
    branches: ["prod"]

concurrency:
  group: ${{ github.ref == 'refs/heads/prod' && format('ci-prod-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test_ci.yml
    secrets: inherit

# TODO: Uncomment when ready
#  deploy:
#    if: "github.event.repository.fork == false"
#    needs: [test]
#    name: 🚀 Deploy web app
#    uses: ./.github/workflows/deploy.yml
#    secrets: inherit
