name: TestCI

defaults:
  run: {shell: bash}

on:
  push:
    branches: ["main"]
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('main-test-{0}', github.sha) || format('test-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  testing:
    name: 🛠️ Run Testing and Pre Buiild
    runs-on: macos-latest

    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v4

      - name: 🛠️ Setup/ Use Node.js 20.x
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.x

      - name: 🛠️ Setup/ Install pnpm 9.7.0 manually
        run: npm install -g pnpm@9.7.0

      - name: 🛠️ Setup/ Install frontend dependencies
        run: |
          pnpm config set store-dir ~/.pnpm-store
          pnpm install --prefer-frozen-lockfile --ignore-scripts

      - name: 📐 Run Linter
        run: pnpm lint

      - name: 📐 Run Type checking
        run: pnpm types:check

      - name: 📐 Run unit tests
        run: pnpm test

      - name: 🔨 Run build client
        run: pnpm build

      - name: 🛡️ Run prune
        run: pnpm prune --prod --ignore-scripts

